---
proxy-providers:
  allProxy:
    type: file
    path: ./proxy_provider/allProxy.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: Game
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - allProxy
- name: BlockHost
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - REJECT
  use:
  - allProxy
- name: Umum
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - allProxy
- name: Umum-URLTest
  type: url-test
  use:
  - allProxy
  url: 'http://www.gstatic.com/generate_204'
  interval: 10
- name: Umum-LB
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - allProxy
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Umum-FB
  type: fallback
  lazy: true
  disable-udp: false
  use:
  - allProxy
  url: http://www.gstatic.com/generate_204
  interval: '30'
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
unified-delay: true
external-controller: 0.0.0.0:9090
secret: telekulo
bind-address: 0.0.0.0
external-ui: ui
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - tcp://1.1.1.1#DNS-SETTING
  - 1.1.1.1#DNS-SETTING
  - https://dns.cloudflare.com/dns-query#DNS-SETTING&h3=true
  - tls://one.one.one.one#DNS-SETTING
  fallback:
  - tcp://1.1.1.1#DNS-SETTING
  - 1.1.1.1#DNS-SETTING
  - https://dns.cloudflare.com/dns-query#DNS-SETTING&h3=true
  - tls://one.one.one.one#DNS-SETTING
  default-nameserver:
  - 112.215.198.248
  - 112.215.198.254
  proxy-server-nameserver:
  - tcp://1.1.1.1#DNS-SETTING
  - 1.1.1.1#DNS-SETTING
  - https://dns.cloudflare.com/dns-query#DNS-SETTING&h3=true
  - tls://one.one.one.one#DNS-SETTING
  - 112.215.198.248
  - 112.215.198.254
profile:
  store-selected: true
rules:
#- RULE-SET,YTAds,BlockHostx
- RULE-SET,Game,Game
- RULE-SET,Block,BlockHost
#- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Umum,Umum
- MATCH,GLOBAL
rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./rule_provider/game.yaml
  Block:
    type: file
    behavior: classical
    path: ./rule_provider/blockedHost2.yaml
  Umum:
    type: file
    behavior: classical
    path: ./rule_provider/umum.yaml
tproxy-port: 7895
tun:
  enable: true
